### ISSUE TITLE
could it support the css module

### ISSUE THREAD

**Issue by Just-focus** [velopert/react-webpack2-skeleton#2]
i wanna to write the different components with the same className , will it affect the style of components, if it is not support ,could u tell me how to config it,Thanks

**Comment by velopert** [comment]
In this project, I am using sass-loader, so what you can do is using **nesting** feature of sass.

You can easily do this by:

```scss
.ComponentA {
    .some-shared-class {
    }
}

.ComponentB {
   .some-shared-class {
   }
}
```

I recommend you to create separated scss file per each component.

If you don't like this, I think you should reconfigure the css-loader from webpack.

P.S. Sorry for late reply.. I guess you might already have solved the issue by this time.
